/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CombineRouteImport } from './routes/combine'
import { Route as RoundWarmupRouteImport } from './routes/round-warmup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaySoloRouteImport } from './routes/play.solo'
import { Route as PlayGameRouteImport } from './routes/play.game'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingSignupRouteImport } from './routes/onboarding.signup'
import { Route as OnboardingNameRouteImport } from './routes/onboarding.name'
import { Route as OnboardingBagRouteImport } from './routes/onboarding.bag'
import { Route as GamesGridGameRouteImport } from './routes/games.grid-game'
import { Route as GamesFairwayGameRouteImport } from './routes/games.fairway-game'
import { Route as GamesClosestToPinRouteImport } from './routes/games.closest-to-pin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UpgradeRouteImport } from './routes/upgrade'

const CombineRoute = CombineRouteImport.update({
  id: '/combine',
  path: '/combine',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundWarmupRoute = RoundWarmupRouteImport.update({
  id: '/round-warmup',
  path: '/round-warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySoloRoute = PlaySoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => PlayRoute,
} as any)
const PlayGameRoute = PlayGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => PlayRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignupRoute = OnboardingSignupRouteImport.update({
  id: '/onboarding/signup',
  path: '/onboarding/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNameRoute = OnboardingNameRouteImport.update({
  id: '/onboarding/name',
  path: '/onboarding/name',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBagRoute = OnboardingBagRouteImport.update({
  id: '/onboarding/bag',
  path: '/onboarding/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGridGameRoute = GamesGridGameRouteImport.update({
  id: '/grid-game',
  path: '/grid-game',
  getParentRoute: () => GamesRoute,
} as any)
const GamesFairwayGameRoute = GamesFairwayGameRouteImport.update({
  id: '/fairway-game',
  path: '/fairway-game',
  getParentRoute: () => GamesRoute,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesClosestToPinRoute = GamesClosestToPinRouteImport.update({
  id: '/closest-to-pin',
  path: '/closest-to-pin',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upgrade': typeof UpgradeRoute
  '/round-warmup': typeof RoundWarmupRoute
  '/games/closest-to-pin': typeof GamesClosestToPinRoute
  '/games/fairway-game': typeof GamesFairwayGameRoute
  '/games/grid-game': typeof GamesGridGameRoute
  '/onboarding/bag': typeof OnboardingBagRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/play/game': typeof PlayGameRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upgrade': typeof UpgradeRoute
  '/round-warmup': typeof RoundWarmupRoute
  '/games/closest-to-pin': typeof GamesClosestToPinRoute
  '/games/fairway-game': typeof GamesFairwayGameRoute
  '/games/grid-game': typeof GamesGridGameRoute
  '/onboarding/bag': typeof OnboardingBagRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/play/game': typeof PlayGameRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upgrade': typeof UpgradeRoute
  '/round-warmup': typeof RoundWarmupRoute
  '/games/closest-to-pin': typeof GamesClosestToPinRoute
  '/games/fairway-game': typeof GamesFairwayGameRoute
  '/games/grid-game': typeof GamesGridGameRoute
  '/onboarding/bag': typeof OnboardingBagRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/play/game': typeof PlayGameRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combine'
    | '/games'
    | '/login'
    | '/play'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/upgrade'
    | '/round-warmup'
    | '/games/closest-to-pin'
    | '/games/fairway-game'
    | '/games/grid-game'
    | '/onboarding/bag'
    | '/onboarding/name'
    | '/onboarding/signup'
    | '/onboarding/welcome'
    | '/play/game'
    | '/play/solo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combine'
    | '/games'
    | '/login'
    | '/play'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/upgrade'
    | '/round-warmup'
    | '/games/closest-to-pin'
    | '/games/fairway-game'
    | '/games/grid-game'
    | '/onboarding/bag'
    | '/onboarding/name'
    | '/onboarding/signup'
    | '/onboarding/welcome'
    | '/play/game'
    | '/play/solo'
  id:
    | '__root__'
    | '/'
    | '/combine'
    | '/games'
    | '/login'
    | '/play'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/upgrade'
    | '/round-warmup'
    | '/games/closest-to-pin'
    | '/games/fairway-game'
    | '/games/grid-game'
    | '/onboarding/bag'
    | '/onboarding/name'
    | '/onboarding/signup'
    | '/onboarding/welcome'
    | '/play/game'
    | '/play/solo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombineRoute: typeof CombineRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpgradeRoute: typeof UpgradeRoute
  RoundWarmupRoute: typeof RoundWarmupRoute
  OnboardingBagRoute: typeof OnboardingBagRoute
  OnboardingNameRoute: typeof OnboardingNameRoute
  OnboardingSignupRoute: typeof OnboardingSignupRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/combine': {
      id: '/combine'
      path: '/combine'
      fullPath: '/combine'
      preLoaderRoute: typeof CombineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round-warmup': {
      id: '/round-warmup'
      path: '/round-warmup'
      fullPath: '/round-warmup'
      preLoaderRoute: typeof RoundWarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/solo': {
      id: '/play/solo'
      path: '/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof PlaySoloRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/game': {
      id: '/play/game'
      path: '/game'
      fullPath: '/play/game'
      preLoaderRoute: typeof PlayGameRouteImport
      parentRoute: typeof PlayRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/signup': {
      id: '/onboarding/signup'
      path: '/onboarding/signup'
      fullPath: '/onboarding/signup'
      preLoaderRoute: typeof OnboardingSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/name': {
      id: '/onboarding/name'
      path: '/onboarding/name'
      fullPath: '/onboarding/name'
      preLoaderRoute: typeof OnboardingNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/bag': {
      id: '/onboarding/bag'
      path: '/onboarding/bag'
      fullPath: '/onboarding/bag'
      preLoaderRoute: typeof OnboardingBagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/grid-game': {
      id: '/games/grid-game'
      path: '/grid-game'
      fullPath: '/games/grid-game'
      preLoaderRoute: typeof GamesGridGameRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/fairway-game': {
      id: '/games/fairway-game'
      path: '/fairway-game'
      fullPath: '/games/fairway-game'
      preLoaderRoute: typeof GamesFairwayGameRouteImport
      parentRoute: typeof GamesRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/closest-to-pin': {
      id: '/games/closest-to-pin'
      path: '/closest-to-pin'
      fullPath: '/games/closest-to-pin'
      preLoaderRoute: typeof GamesClosestToPinRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesClosestToPinRoute: typeof GamesClosestToPinRoute
  GamesFairwayGameRoute: typeof GamesFairwayGameRoute
  GamesGridGameRoute: typeof GamesGridGameRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesClosestToPinRoute: GamesClosestToPinRoute,
  GamesFairwayGameRoute: GamesFairwayGameRoute,
  GamesGridGameRoute: GamesGridGameRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface PlayRouteChildren {
  PlayGameRoute: typeof PlayGameRoute
  PlaySoloRoute: typeof PlaySoloRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayGameRoute: PlayGameRoute,
  PlaySoloRoute: PlaySoloRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombineRoute: CombineRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRouteWithChildren,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpgradeRoute: UpgradeRoute,
  RoundWarmupRoute: RoundWarmupRoute,
  OnboardingBagRoute: OnboardingBagRoute,
  OnboardingNameRoute: OnboardingNameRoute,
  OnboardingSignupRoute: OnboardingSignupRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
